micronaut:
  application:
    name: demo
datasources:
  default:
    url: jdbc:h2:mem:devDb;LOCK_TIMEOUT=10000
    username: sa
    password: ''
    driverClassName: org.h2.Driver
    schema-generate: NONE
    dialect: H2
netty:
  default:
    allocator:
      max-order: 3
flyway:
  datasources:
    default:
      enabled: true
